export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const HANDLE_OPEN_CART = "HANDLE_OPEN_CART";
export const HANDLE_OPEN_FILTER = "HANDLE_OPEN_FILTER";
export const CLOSE_CART_AND_FILTER = "CLOSE_CART_AND_FILTER";
